apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-simple
spec:
  ingressClassName: contour
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: simple-svc
                port:
                  number: 80
