apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: simple-replicaset
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: simple-app
  template: 
    metadata: 
      labels:
        app: simple-app
    spec: 
      containers:
        - name: simple-java-app
          image: romajanlyi/simple-java-app
          ports:
            - containerPort: 8080