apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deploy
spec:
  selector:
    matchLabels:
      app: simple
  replicas: 4
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: simple
    spec:
      containers:
      - name: simple-java
        image: romajanlyi/simple-java-app:with-secret
        ports:
          - containerPort: 8080
        env:
          - name: SECRET_WORD
            valueFrom:
              secretKeyRef:
                name: simple-secret
                key: secret-word
          - name: TEST_2_D_WORD
            valueFrom:
              secretKeyRef:
                name: simple-secret
                key: secret-second-word
        readinessProbe:
          failureThreshold: 3
          httpGet:
            port: 8082
            path: /management-simple-spring/monitoring/health
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1
        livenessProbe:
          initialDelaySeconds: 10
          timeoutSeconds: 1
          httpGet:
            path: /management-simple-spring/monitoring/beans
            port: 8082
          periodSeconds: 10
          failureThreshold: 3
        resources:
          limits:
            memory: "300Mi"
          requests:
            memory: "100Mi"
        volumeMounts:
          - name: simple-spring-config
            mountPath: /app/target/config
      volumes:
        - name: simple-spring-config
          configMap:
            name: simple-spring-config