apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deploy
spec:
  selector:
    matchLabels:
      app: simple
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: simple
    spec:
      containers:
      - name: simple-java
        image: romajanlyi/simple-java-app:1.1
        ports:
          - containerPort: 8080
        readinessProbe:
          failureThreshold: 3
          httpGet:
            port: 8080
            path: /bye
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1