apiVersion: v1
kind: Service
metadata:
  name: node-remote-debug
  namespace: simple
spec:
  type: NodePort
  selector:
    app: simple
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 5005
      nodePort: 30505
    - name: http2
      protocol: TCP
      port: 8081
      targetPort: 8080
      nodePort: 30504
