#Позволяет конфигать порты и хосты istio ингресса
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: simple-ingress-gw
  namespace: simple
spec:
  selector:
#    Селектим под Ingress-а для которого будет эта настройка открытия портов
    istio: ingressgateway
  servers:
    - port:
#        Открываем порт на ингрессе
        number: 80
        name: http-dev
        protocol: HTTP
      hosts:
#         (хост самого ингресса)
        - 'simple.dev' #Принимать запросы только от заголовков Host
    - port:
        number: 80
        name: http-prod
        protocol: HTTP
      hosts:
        - 'simple.prod'

