apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: simple-ingress-gw
  namespace: simple
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
    - port:
        number: 15021
        name: http2
        protocol: HTTP
      hosts:
        - "*"
