apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: simple-ingress-vs
  namespace: simple
spec:
  hosts:
    - "simple.dev"
  gateways:
    - simple-ingress-gw
  http:
    - match:
        - uri:
            prefix: /simple-spring/ip
      route:
        - destination:
            host: simple-svc.simple.svc.cluster.local
            port:
              number: 80