apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools: 
      - name: default 
        protocol: layer2 
        addresses: 
          - 194.58.98.140-194.58.98.150