apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: kafka
spec:
  type: NodePort
  ports:
    - port: 9092
      nodePort: 30001
      targetPort: 9092
  selector:
    app: kafka-broker